version: '3.8'

services:
  strongswadn:
    image: jshotyk/alpine-strongswan-vpn:testing
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./config/ipsec.conf:/etc/ipsec.conf
      - ./config/ipsec.secrets:/etc/ipsec.secrets
      #- ./config/serverKey.pem:/etc/ipsec.d/private/serverKey.pem
    container_name: strongswan
